apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: rabbitmq-pod-kill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: fixed-percent
  value: 50
  gracePeriod: 0
  duration: 300s
  selector:
    namespaces:
      - 'rabbit'
    labelSelectors:
      'app': 'rabbitmq'
  scheduler:
    cron: '@every 1m'