apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: scheduled-pod-chaos
spec:
  schedule: '@every 1m30s'
  type: 'PodChaos'
  podChaos:
    action: pod-kill
    mode: fixed-percent
    value: '50'
    gracePeriod: 0
    selector:
      namespaces:
        - 'rabbit'
      labelSelectors:
        'app': 'rabbitmq'