apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-emulation
spec:
  action: netem
  mode: loss
  selector:
    namespaces:
      - dev-stable
    labelSelectors:
      'app': 'dev-stable'
    fieldSelectors:
      'metadata.name': 'producer-pod-<id>'
  loss:
    loss: '30'
    correlation: '10'